# Generated by Django 4.1 on 2022-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_point',
            field=models.IntegerField(default=0),
        ),
    ]
