# Generated by Django 4.1 on 2022-10-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_rename_post_post_content_remove_post_poster'),
        ('my_account', '0002_alter_useraccount_user_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
