# Generated by Django 4.1 on 2022-11-02 12:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='unknown', max_length=63),

        ),
    ]
