# Generated by Django 4.1 on 2022-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0001_initial'),
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='events_joined',
            field=models.ManyToManyField(to='create_event.event'),
        ),
    ]
