# Generated by Django 4.1 on 2022-11-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
        ('landing_page', '0002_useraccount_events_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='events_joined',
            field=models.ManyToManyField(to='timeline.joinevent'),
        ),
    ]
