# Generated by Django 4.1 on 2022-10-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_useraccount_events_joined'),
        ('landing_page', '0003_alter_useraccount_username'),
    ]

    operations = [
    ]
