# Generated by Django 4.1 on 2022-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_remove_useraccount_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='events_joined',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='unknown', max_length=63),
        ),
    ]
