# Generated by Django 4.1 on 2022-10-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_account', '0002_alter_useraccount_user_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('post', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_account.useraccount')),
            ],
        ),
    ]
