# Generated by Django 4.1 on 2022-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
    ]
