# Generated by Django 4.1 on 2022-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_comment_creator_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='creator_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
