# Generated by Django 4.1 on 2022-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment_creator_name_post_creator_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='original_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='original_post_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
