# Generated by Django 4.1 on 2022-10-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_comment_creator_alter_comment_date_and_more'),
        ('forum', '0005_alter_comment_creator_alter_post_creator'),
    ]

    operations = [
    ]
