# Generated by Django 4.1 on 2022-10-31 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment_creator_name_post_creator_name'),
        ('forum', '0006_merge_20221029_1933'),
    ]

    operations = [
    ]
