# Generated by Django 4.1 on 2022-10-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_merge_20221031_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creator_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
