# Generated by Django 4.1 on 2022-11-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_comment_original_post_and_more'),
        ('forum', '0008_alter_comment_creator_name'),
    ]

    operations = [
    ]
