# Generated by Django 4.1 on 2022-11-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(default='')),
                ('users', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='landing_page.useraccount')),
            ],
        ),
    ]
