# Generated by Django 4.1 on 2022-10-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fotoPantai',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
