# Generated by Django 4.1 on 2022-10-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0002_alter_event_fotopantai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fotoPantai',
            field=models.URLField(),
        ),
    ]
